server:
  port: 8180
  http2:
    enabled: true

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    # MySQL本地化
    url: jdbc:mysql://127.0.0.1:3306/porn_tube?useUnicode=true&characterEncoding=UTF-8
    username: user
    password: 1234
  servlet:
    multipart:
      enabled: true
      max-file-size: 100000000MB
      max-request-size: 1024000000MB

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml


logging:
  level:
    com:
      buguagaoshu:
        porntube: debug
  file:
    name: log/spring.log
  logback:
    rollingpolicy:
      max-history: 7